# Generated by Django 4.1 on 2023-03-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
