# Generated by Django 4.1 on 2023-03-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0002_alter_contact_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('position', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('linkedin', models.URLField()),
                ('portfolio', models.URLField()),
                ('choice', models.CharField(choices=[('YES', 'Yes'), ('No', 'No')], default='YES', max_length=3)),
            ],
        ),
    ]
