# Generated by Django 4.1 on 2023-03-17 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0003_career'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career',
        ),
    ]
