# Generated by Django 4.1 on 2023-03-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0005_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='choice1',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='career',
            name='choice2',
            field=models.CharField(max_length=3),
        ),
    ]
