# Generated by Django 4.1 on 2023-03-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0007_alter_career_choice1_alter_career_choice2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='career',
            name='choice2',
        ),
        migrations.AlterField(
            model_name='career',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='career',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='portfolio',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='position',
            field=models.TextField(null=True),
        ),
    ]
