# Generated by Django 4.1 on 2023-03-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0009_career_choice1_career_choice2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='cover_letter',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='career',
            name='resume',
            field=models.FileField(upload_to=''),
        ),
    ]
