# Generated by Django 4.1 on 2023-03-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0011_alter_career_cover_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
