# Generated by Django 4.1 on 2023-03-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0012_alter_career_cover_letter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Career',
        ),
    ]
