# Generated by Django 4.1 on 2023-03-19 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('akuaa', '0014_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='cover_letter',
            field=models.FileField(upload_to='cover_letter-file'),
        ),
        migrations.AlterField(
            model_name='career',
            name='resume',
            field=models.FileField(upload_to='resume-file'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='', upload_to='blog-img')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
