# Generated by Django 4.1 on 2023-03-19 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0016_latestnews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestNews',
        ),
    ]
