# Generated by Django 4.1 on 2023-03-19 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0017_delete_latestnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='LatestNews-img')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.URLField()),
            ],
        ),
    ]
