# Generated by Django 4.1 on 2023-03-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0021_alter_career_choice1_alter_career_choice2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('event', models.CharField(max_length=100)),
                ('event_date', models.CharField(max_length=10)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DJService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='dj-img')),
                ('position', models.CharField(max_length=100)),
                ('content1', models.TextField()),
                ('content2', models.TextField()),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
                ('instagram', models.URLField()),
                ('youtube', models.URLField()),
            ],
        ),
    ]
