# Generated by Django 4.1 on 2023-03-28 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0022_book_djservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DJService',
        ),
    ]
