# Generated by Django 4.1 on 2023-03-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0023_delete_djservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='dj-img')),
                ('position', models.CharField(max_length=100)),
                ('content1', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('content2', models.TextField()),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
                ('instagram', models.URLField()),
                ('youtube', models.URLField()),
            ],
        ),
    ]
