# Generated by Django 4.1 on 2023-03-29 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0024_djservice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DJService',
        ),
    ]
