# Generated by Django 4.1 on 2023-03-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0026_djservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djservice',
            name='book',
        ),
    ]
