# Generated by Django 4.1 on 2023-03-29 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0027_remove_djservice_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
