# Generated by Django 4.1 on 2023-03-29 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0029_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
    ]
