# Generated by Django 4.1 on 2023-04-30 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0030_remove_book_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DJService',
        ),
        migrations.DeleteModel(
            name='LatestNews',
        ),
    ]
