# Generated by Django 4.1 on 2023-04-30 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0031_delete_djservice_delete_latestnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='client-img')),
                ('position', models.CharField(max_length=100)),
                ('content1', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('content2', models.TextField()),
                ('twitter', models.URLField()),
                ('facebook', models.URLField()),
                ('linkedin', models.URLField()),
                ('instagram', models.URLField()),
                ('youtube', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='LatestNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='LatestNews-img')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
