# Generated by Django 4.1 on 2023-04-30 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0032_client_latestnews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='content1',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='client',
            name='content2',
        ),
    ]
