# Generated by Django 4.1 on 2023-05-01 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0033_rename_content1_client_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestNews',
        ),
    ]
