# Generated by Django 4.1 on 2023-05-01 00:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akuaa', '0034_delete_latestnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='HomeClient-img')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
